version: "3.7"

services:
  database_hublocal:
    image: postgres
    container_name: database-database_hublocal
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=hublocal
      - POSTGRES_DB=hublocal
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   networks: host

volumes:
  pgdata:
    driver: local
